mode: DEBUG_OPERATIONS
number_inconsistencies: 0
xcy_inconsistencies: []
xcy_lineages:
- _id: 0
  operations:
  - (0, 0) read(config_db, , res) @ ConfigService
  xcy_dependencies:
  - (0, 0) read(config_db, , res) @ ConfigService
  xcy_missing_dependencies: []
