mode: DEBUG_OPERATIONS
number_inconsistencies: 0
xcy_inconsistencies: []
xcy_lineages:
- _id: 0
  operations:
  - (0, 0) read(config_db, query, res) @ ConfigService
  - (0, 1) write(config_db, conf, conf) @ ConfigService
  xcy_dependencies:
  - (0, 1) write(config_db, conf, conf) @ ConfigService
  xcy_missing_dependencies: []
