mode: DEBUG_OPERATIONS
number_inconsistencies: 0
xcy_inconsistencies: []
xcy_lineages:
- _id: 0
  operations:
  - (0, 0) read(consignprice_db, query, res) @ ConsignPriceService
  - (0, 1) write(consignprice_db, priceConfig, priceConfig) @ ConsignPriceService
  xcy_dependencies:
  - (0, 1) write(consignprice_db, priceConfig, priceConfig) @ ConsignPriceService
  - (0, 0) read(consignprice_db, query, res) @ ConsignPriceService
  xcy_missing_dependencies: []
