mode: DEBUG_OPERATIONS
number_inconsistencies: 0
xcy_inconsistencies: []
xcy_lineages:
- _id: 0
  operations:
  - (0, 0) read(trainfood_db, query, res) @ TrainFoodService
  - (0, 1) write(trainfood_db, tf, tf) @ TrainFoodService
  xcy_dependencies:
  - (0, 1) write(trainfood_db, tf, tf) @ TrainFoodService
  - (0, 0) read(trainfood_db, query, res) @ TrainFoodService
  xcy_missing_dependencies: []
