mode: DEBUG_OPERATIONS
number_inconsistencies: 0
xcy_inconsistencies: []
xcy_lineages:
- _id: 0
  operations:
  - (0, 0) read(train_db, query, res) @ TrainService
  xcy_dependencies: []
  xcy_missing_dependencies: []
