mode: DEBUG_OPERATIONS
number_inconsistencies: 0
xcy_inconsistencies: []
xcy_lineages:
- _id: 0
  operations:
  - (0, 0) read(trainfood_db, , res) @ TrainFoodService
  xcy_dependencies:
  - (0, 0) read(trainfood_db, , res) @ TrainFoodService
  xcy_missing_dependencies: []
