BillingService:
- fields:
    bill_db: NoSQLDatabase
- services: {}
- datastores:
    billing_db: NoSQLDatabase
CartService:
- fields:
    cart_db: NoSQLDatabase
    order_service: OrderService
- services:
    OrderService: threechain2.OrderService
- datastores:
    cart_db: NoSQLDatabase
OrderService:
- fields:
    billing_service: BillingService
    order_db: NoSQLDatabase
    shipment_queue: Queue
    stock_service: StockService
- services:
    BillingService: threechain2.BillingService
    StockService: threechain2.StockService
- datastores:
    order_db: NoSQLDatabase
    shipment_queue: Queue
ShipmentService:
- fields:
    num_workers: 4 int
    order_service: OrderService
    shipment_db: NoSQLDatabase
    shipment_queue: Queue
- services:
    OrderService: threechain2.OrderService
- datastores:
    shipment_db: NoSQLDatabase
    shipment_queue: Queue
StockService:
- fields:
    stock_db: NoSQLDatabase
- services: {}
- datastores:
    stock_db: NoSQLDatabase
