ANALYTICS_DB:
- type: NoSQLDatabase
- kind: MongoDB
- dependencies:
  - analytics_queue
  - posts_db
- schema:
  - fields:
    - document: postnotification.Analytics struct{PostID int64}
  - unfolded_fields:
    - Analytics: postnotification.Analytics struct{PostID int64}
    - Analytics.PostID: int64
  - foreign_fields:
    - Analytics:
      - ANALYTICS_QUEUE.TriggerAnalyticsMessage.PostID
      - POSTS_DB.Post.PostID
    - Analytics.PostID:
      - ANALYTICS_QUEUE.TriggerAnalyticsMessage.PostID
      - POSTS_DB.Post.PostID
ANALYTICS_QUEUE:
- type: Queue
- kind: RabbitMQ
- dependencies:
  - posts_db
- schema:
  - fields:
    - message: postnotification.TriggerAnalyticsMessage struct{PostID string}
  - unfolded_fields:
    - TriggerAnalyticsMessage: postnotification.TriggerAnalyticsMessage struct{PostID string}
    - TriggerAnalyticsMessage.PostID: string
  - foreign_fields:
    - TriggerAnalyticsMessage:
      - POSTS_DB.Post.PostID
    - TriggerAnalyticsMessage.PostID:
      - POSTS_DB.Post.PostID
NOTIFICATIONS_QUEUE:
- type: Queue
- kind: RabbitMQ
- dependencies:
  - posts_db
  - analytics_queue
  - analytics_db
- schema:
  - fields:
    - message: postnotification.Message struct{ReqID string, PostID string, Timestamp string}
  - unfolded_fields:
    - Message: postnotification.Message struct{ReqID string, PostID string, Timestamp string}
    - Message.ReqID: string
    - Message.PostID: string
    - Message.Timestamp: string
  - foreign_fields:
    - Message:
      - ANALYTICS_DB.Analytics.PostID
      - ANALYTICS_QUEUE.TriggerAnalyticsMessage.PostID
      - POSTS_DB.Post.PostID
      - POSTS_DB.Post.ReqID
    - Message.ReqID:
      - POSTS_DB.Post.ReqID
    - Message.PostID:
      - ANALYTICS_DB.Analytics.PostID
      - ANALYTICS_QUEUE.TriggerAnalyticsMessage.PostID
      - POSTS_DB.Post.PostID
POSTS_CACHE:
- type: Cache
- kind: Redis
- dependencies: []
- schema:
  - fields: []
  - unfolded_fields: []
  - foreign_fields: []
POSTS_DB:
- type: NoSQLDatabase
- kind: MongoDB
- dependencies: []
- schema:
  - fields:
    - document: postnotification.Post struct{ReqID int64, PostID int64, Text string, Mentions []string, Timestamp int64, Creator postnotification.Creator struct{Username string}}
  - unfolded_fields:
    - Post: postnotification.Post struct{ReqID int64, PostID int64, Text string, Mentions []string, Timestamp int64, Creator postnotification.Creator struct{Username string}}
    - Post.ReqID: int64
    - Post.PostID: int64
    - Post.Text: string
    - Post.Mentions: '[]string'
    - Post.Timestamp: int64
    - Post.Creator: postnotification.Creator struct{Username string}
    - Post.Creator.Username: string
  - foreign_fields: []
TIMELINE_CACHE:
- type: Cache
- kind: Redis
- dependencies:
  - posts_db
  - notifications_queue
  - analytics_queue
  - analytics_db
- schema:
  - fields:
    - key: string
    - value: Timeline
  - unfolded_fields: []
  - foreign_fields:
    - key:
      - NOTIFICATIONS_QUEUE.Message.ReqID
      - POSTS_DB.Post.ReqID
    - value:
      - ANALYTICS_DB.Analytics.PostID
      - ANALYTICS_QUEUE.TriggerAnalyticsMessage.PostID
      - NOTIFICATIONS_QUEUE.Message.PostID
      - NOTIFICATIONS_QUEUE.Message.ReqID
      - POSTS_DB.Post.PostID
      - POSTS_DB.Post.ReqID
