AnalyticsService:
- fields:
    analytics_db: NoSQLDatabase
    analytics_queue: Queue
    num_workers: 4 int
- services: {}
- datastores:
    analytics_db: NoSQLDatabase
    analytics_queue: Queue
NotifyService:
- fields:
    notifications_queue: Queue
    num_workers: 4 int
    storage_service: StorageService
- services:
    StorageService: postnotification.StorageService
- datastores:
    notifications_queue: Queue
StorageService:
- fields:
    analytics_queue: Queue
    analytics_service: AnalyticsService
    posts_cache: Cache
    posts_db: NoSQLDatabase
- services:
    AnalyticsService: postnotification.AnalyticsService
- datastores:
    analytics_queue: Queue
    posts_cache: Cache
    posts_db: NoSQLDatabase
TimelineService:
- fields:
    storage_service: StorageService
    timeline_cache: Cache
- services:
    StorageService: postnotification.StorageService
- datastores:
    timeline_cache: Cache
UploadService:
- fields:
    notifications_queue: Queue
    storage_service: StorageService
    timeline_cache: Cache
- services:
    StorageService: postnotification.StorageService
- datastores:
    notifications_queue: Queue
    timeline_cache: Cache
