NotifyService:
- fields:
    numWorkers: 4 int
    queue: Queue
    storageService: StorageService
- services:
    StorageService: postnotification.StorageService
- datastores:
    notification_queue: Queue
StorageService:
- fields:
    cache: Cache
    db: NoSQLDatabase
- services: {}
- datastores:
    post_cache: Cache
    post_db: Cache
UploadService:
- fields:
    queue: Queue
    storageService: StorageService
- services:
    StorageService: postnotification.StorageService
- datastores:
    notification_queue: Queue
