(*ConfigServiceImpl).Create(ctx context.Context, conf config.Config struct{Name string, Value string, Description string}):
  block 0 (Body):
  - '[INLINE] db NoSQLDatabase'
  - c (*config.ConfigServiceImpl struct{db NoSQLDatabase})
  - ctx context.Context
  - conf config.Config struct{Name string, Value string, Description string}
  - coll NoSQLCollection {database = "config", collection = "config"}
  - err .error
(*ConfigServiceImpl).Delete(ctx context.Context, name string):
  block 0 (Body):
  - '[INLINE] db NoSQLDatabase'
  - c (*config.ConfigServiceImpl struct{db NoSQLDatabase})
  - ctx context.Context
  - name string
  - coll NoSQLCollection {database = "config", collection = "config"}
  - err .error
(*ConfigServiceImpl).Find(ctx context.Context, name string):
  block 0 (Body):
  - '[INLINE] db NoSQLDatabase'
  - c (*config.ConfigServiceImpl struct{db NoSQLDatabase})
  - ctx context.Context
  - name string
  - coll NoSQLCollection {database = "config", collection = "config"}
  - err .error
(*ConfigServiceImpl).FindAll(ctx context.Context):
  block 0 (Body):
  - '[INLINE] db NoSQLDatabase'
  - c (*config.ConfigServiceImpl struct{db NoSQLDatabase})
  - ctx context.Context
  - coll NoSQLCollection {database = "config", collection = "config"}
  - err .error
(*ConfigServiceImpl).Update(ctx context.Context, conf config.Config struct{Name string, Value string, Description string}):
  block 0 (Body):
  - '[INLINE] db NoSQLDatabase'
  - c (*config.ConfigServiceImpl struct{db NoSQLDatabase})
  - ctx context.Context
  - conf config.Config struct{Name string, Value string, Description string}
  - coll NoSQLCollection {database = "config", collection = "config"}
  - err .error
.NewConfigServiceImpl(ctx context.Context, db NoSQLDatabase):
  block 0 (Body):
  - ctx context.Context
  - db NoSQLDatabase
