(*ConfigServiceImpl).Create(ctx context.Context, conf config.Config struct{Name string, Value string, Description string}):
  block 11 (IfDone):
  - (inline) db NoSQLDatabase
  - c (*config.ConfigServiceImpl struct{db NoSQLDatabase})
  - ctx context.Context
  - |-
    (inline) Name string -->
       W-TAINTED 1x = (CONFIG_DB.Config.Name)
  - |-
    (inline) Name string -->
       W-TAINTED 1x = (CONFIG_DB.Config.Name)
  - |-
    conf config.Config struct{Name string, Value string, Description string} -->
       W-TAINTED 1x = (CONFIG_DB.Config)
  - coll NoSQLCollection {database = "config", collection = "config"}
  - err .error
  - (inline) "name" string
  - (inline) "name" string
  - (inline) struct{ "name" string, Name string}
  - query primitive.D
  - res NoSQLCursor {database = "config", collection = "config"}
  - err .error
  - saved_conf config.Config struct{Name string, Value string, Description string}
  - exists bool
  - err .error
(*ConfigServiceImpl).Delete(ctx context.Context, name string):
  block 2 (IfDone):
  - (inline) db NoSQLDatabase
  - c (*config.ConfigServiceImpl struct{db NoSQLDatabase})
  - ctx context.Context
  - name string
  - coll NoSQLCollection {database = "config", collection = "config"}
  - err .error
  - (inline) string
  - (inline) struct{ "name" string, string}
  - query primitive.D
(*ConfigServiceImpl).Find(ctx context.Context, name string):
  block 11 (IfDone):
  - (inline) db NoSQLDatabase
  - c (*config.ConfigServiceImpl struct{db NoSQLDatabase})
  - ctx context.Context
  - name string
  - coll NoSQLCollection {database = "config", collection = "config"}
  - err .error
  - (inline) string
  - (inline) struct{ "name" string, string}
  - query primitive.D
  - |-
    res NoSQLCursor {database = "config", collection = "config"} -->
       R-TAINTED 2x = (CONFIG_DB.document, CONFIG_DB.NoSQLCursor)
  - err .error
  - conf config.Config struct{Name string, Value string, Description string}
  - exists bool
  - err .error
(*ConfigServiceImpl).FindAll(ctx context.Context):
  block 8 (IfDone):
  - (inline) db NoSQLDatabase
  - c (*config.ConfigServiceImpl struct{db NoSQLDatabase})
  - ctx context.Context
  - coll NoSQLCollection {database = "config", collection = "config"}
  - err .error
  - configs []config.Config struct{Name string, Value string, Description string}
  - res NoSQLCursor {database = "config", collection = "config"}
  - err .error
  - err .error
(*ConfigServiceImpl).Update(ctx context.Context, conf config.Config struct{Name string, Value string, Description string}):
  block 2 (IfDone):
  - (inline) db NoSQLDatabase
  - c (*config.ConfigServiceImpl struct{db NoSQLDatabase})
  - ctx context.Context
  - (inline) Name string
  - (inline) Name string
  - conf config.Config struct{Name string, Value string, Description string}
  - coll NoSQLCollection {database = "config", collection = "config"}
  - err .error
  - (inline) "name" string
  - (inline) "name" string
  - (inline) struct{ "name" string, Name string}
  - query primitive.D
.NewConfigServiceImpl(ctx context.Context, db NoSQLDatabase):
  block 0 (Body):
  - ctx context.Context
  - db NoSQLDatabase
