(*TrainServiceImpl).AllTrains(ctx context.Context):
  block 8 (IfDone):
  - (inline) db NoSQLDatabase
  - ts (*train.TrainServiceImpl struct{db NoSQLDatabase})
  - ctx context.Context
  - trains []train.TrainType struct{ID string, Name string, EconomyClass int64, ComfortClass int64, AvgSpeed int64}
  - coll NoSQLCollection {database = "train", collection = "train"}
  - err .error
  - res NoSQLCursor {database = "train", collection = "train"}
  - err .error
  - err .error
(*TrainServiceImpl).Create(ctx context.Context, tt train.TrainType struct{ID string, Name string, EconomyClass int64, ComfortClass int64, AvgSpeed int64}):
 block 14 (IfDone):
  - (inline) db NoSQLDatabase
  - ts (*train.TrainServiceImpl struct{db NoSQLDatabase})
  - ctx context.Context
  - |-
    (inline) Name string -->
       W-TAINTED 1x = (TRAIN_DB.TrainType.Name)
  - |-
    (inline) Name string -->
       W-TAINTED 1x = (TRAIN_DB.TrainType.Name)
  - |-
    tt train.TrainType struct{ID string, Name string, EconomyClass int64, ComfortClass int64, AvgSpeed int64} -->
       W-TAINTED 1x = (TRAIN_DB.TrainType)
  - coll NoSQLCollection {database = "train", collection = "train"}
  - err .error
  - (inline) "name" string
  - (inline) "name" string
  - (inline) struct{ "name" string, Name string}
  - query primitive.D
  - res NoSQLCursor {database = "train", collection = "train"}
  - err .error
  - saved_tt train.TrainType struct{ID string, Name string, EconomyClass int64, ComfortClass int64, AvgSpeed int64}
  - exists bool
  - err .error
  - err .error
(*TrainServiceImpl).Delete(ctx context.Context, id string):
  block 5 (IfDone):
  - (inline) db NoSQLDatabase
  - ts (*train.TrainServiceImpl struct{db NoSQLDatabase})
  - ctx context.Context
  - id string
  - coll NoSQLCollection {database = "train", collection = "train"}
  - err .error
  - err .error
(*TrainServiceImpl).Retrieve(ctx context.Context, id string):
  block 11 (IfDone):
  - (inline) db NoSQLDatabase
  - ts (*train.TrainServiceImpl struct{db NoSQLDatabase})
  - ctx context.Context
  - id string
  - coll NoSQLCollection {database = "train", collection = "train"}
  - err .error
  - (inline) string
  - (inline) struct{ "id" string, string}
  - query primitive.D
  - |-
    res NoSQLCursor {database = "train", collection = "train"} -->
       R-TAINTED 2x = (TRAIN_DB.document, TRAIN_DB.NoSQLCursor)
  - err .error
  - tt train.TrainType struct{ID string, Name string, EconomyClass int64, ComfortClass int64, AvgSpeed int64}
  - exists bool
  - err .error
(*TrainServiceImpl).RetrieveByName(ctx context.Context, name string):
  block 11 (IfDone):
  - (inline) db NoSQLDatabase
  - ts (*train.TrainServiceImpl struct{db NoSQLDatabase})
  - ctx context.Context
  - name string
  - coll NoSQLCollection {database = "train", collection = "train"}
  - err .error
  - (inline) string
  - (inline) struct{ "name" string, string}
  - query primitive.D
  - |-
    res NoSQLCursor {database = "train", collection = "train"} -->
       R-TAINTED 2x = (TRAIN_DB.document, TRAIN_DB.NoSQLCursor)
  - err .error
  - tt train.TrainType struct{ID string, Name string, EconomyClass int64, ComfortClass int64, AvgSpeed int64}
  - exists bool
  - err .error
(*TrainServiceImpl).RetrieveByNames(ctx context.Context, names []string):
  block 0 (Body):
  - (inline) db NoSQLDatabase
  - ts (*train.TrainServiceImpl struct{db NoSQLDatabase})
  - ctx context.Context
  - names []string
  - trainTypes []train.TrainType struct{ID string, Name string, EconomyClass int64, ComfortClass int64, AvgSpeed int64}
(*TrainServiceImpl).Update(ctx context.Context, ttype train.TrainType struct{ID string, Name string, EconomyClass int64, ComfortClass int64, AvgSpeed int64}):
 block 2 (IfDone):
  - (inline) db NoSQLDatabase
  - ts (*train.TrainServiceImpl struct{db NoSQLDatabase})
  - ctx context.Context
  - (inline) ID string
  - (inline) ID string
  - ttype train.TrainType struct{ID string, Name string, EconomyClass int64, ComfortClass int64, AvgSpeed int64}
  - coll NoSQLCollection {database = "train", collection = "train"}
  - err .error
  - (inline) "id" string
  - (inline) "id" string
  - (inline) struct{ "id" string, ID string}
  - query primitive.D
.NewTrainServiceImpl(ctx context.Context, db NoSQLDatabase):
  block 0 (Body):
  - ctx context.Context
  - db NoSQLDatabase
