(*TrainServiceImpl).AllTrains(ctx context.Context):
  block 0 (Body):
  - '[INLINE] db NoSQLDatabase'
  - ts (*train.TrainServiceImpl struct{db NoSQLDatabase})
  - ctx context.Context
  - trains []train.TrainType struct{ID string, Name string, EconomyClass int64, ComfortClass int64, AvgSpeed int64}
  - coll NoSQLCollection {database = "train", collection = "train"}
  - err .error
(*TrainServiceImpl).Create(ctx context.Context, tt train.TrainType struct{ID string, Name string, EconomyClass int64, ComfortClass int64, AvgSpeed int64}):
 block 0 (Body):
  - '[INLINE] db NoSQLDatabase'
  - ts (*train.TrainServiceImpl struct{db NoSQLDatabase})
  - ctx context.Context
  - '[INLINE] Name string --> (TAINTED 1x) --> [TRAIN_DB.TrainType.Name]'
  - '[INLINE] Name string --> (TAINTED 1x) --> [TRAIN_DB.TrainType.Name]'
  - tt train.TrainType struct{ID string, Name string, EconomyClass int64, ComfortClass int64, AvgSpeed int64} --> (TAINTED 1x) --> [TRAIN_DB.TrainType]
  - coll NoSQLCollection {database = "train", collection = "train"}
  - err .error
(*TrainServiceImpl).Delete(ctx context.Context, id string):
  block 0 (Body):
  - '[INLINE] db NoSQLDatabase'
  - ts (*train.TrainServiceImpl struct{db NoSQLDatabase})
  - ctx context.Context
  - id string
  - coll NoSQLCollection {database = "train", collection = "train"}
  - err .error
(*TrainServiceImpl).Retrieve(ctx context.Context, id string):
  block 0 (Body):
  - '[INLINE] db NoSQLDatabase'
  - ts (*train.TrainServiceImpl struct{db NoSQLDatabase})
  - ctx context.Context
  - id string
  - coll NoSQLCollection {database = "train", collection = "train"}
  - err .error
(*TrainServiceImpl).RetrieveByName(ctx context.Context, name string):
  block 0 (Body):
  - '[INLINE] db NoSQLDatabase'
  - ts (*train.TrainServiceImpl struct{db NoSQLDatabase})
  - ctx context.Context
  - name string
  - coll NoSQLCollection {database = "train", collection = "train"}
  - err .error
(*TrainServiceImpl).RetrieveByNames(ctx context.Context, names []string):
  block 0 (Body):
  - '[INLINE] db NoSQLDatabase'
  - ts (*train.TrainServiceImpl struct{db NoSQLDatabase})
  - ctx context.Context
  - names []string
  - trainTypes []train.TrainType struct{ID string, Name string, EconomyClass int64, ComfortClass int64, AvgSpeed int64}
(*TrainServiceImpl).Update(ctx context.Context, ttype train.TrainType struct{ID string, Name string, EconomyClass int64, ComfortClass int64, AvgSpeed int64}):
 block 0 (Body):
  - '[INLINE] db NoSQLDatabase'
  - ts (*train.TrainServiceImpl struct{db NoSQLDatabase})
  - ctx context.Context
  - '[INLINE] ID string'
  - '[INLINE] ID string'
  - ttype train.TrainType struct{ID string, Name string, EconomyClass int64, ComfortClass int64, AvgSpeed int64}
  - coll NoSQLCollection {database = "train", collection = "train"}
  - err .error
.NewTrainServiceImpl(ctx context.Context, db NoSQLDatabase):
  block 0 (Body):
  - ctx context.Context
  - db NoSQLDatabase
