(*TrainFoodServiceImpl).Cleanup(ctx context.Context):
  block 0 (Body):
  - '[INLINE] db NoSQLDatabase'
  - t (*trainfood.TrainFoodServiceImpl struct{db NoSQLDatabase})
  - ctx context.Context
  - coll NoSQLCollection {database = "trainfood", collection = "trainfood"}
  - err .error
(*TrainFoodServiceImpl).CreateTrainFood(ctx context.Context, tf trainfood.TrainFood struct{ID string, TripID string, Foods []food.Food struct{Name string, Price float64}}):
 block 0 (Body):
  - '[INLINE] db NoSQLDatabase'
  - t (*trainfood.TrainFoodServiceImpl struct{db NoSQLDatabase})
  - ctx context.Context
  - tf trainfood.TrainFood struct{ID string, TripID string, Foods []food.Food struct{Name string, Price float64}} --> (TAINTED 1x) --> [TRAINFOOD_DB.TrainFood]
  - coll NoSQLCollection {database = "trainfood", collection = "trainfood"}
  - err .error
(*TrainFoodServiceImpl).ListTrainFood(ctx context.Context):
  block 0 (Body):
  - '[INLINE] db NoSQLDatabase'
  - t (*trainfood.TrainFoodServiceImpl struct{db NoSQLDatabase})
  - ctx context.Context
  - coll NoSQLCollection {database = "trainfood", collection = "trainfood"}
  - err .error
(*TrainFoodServiceImpl).ListTrainFoodByTripID(ctx context.Context, tripid string):
  block 0 (Body):
  - '[INLINE] db NoSQLDatabase'
  - t (*trainfood.TrainFoodServiceImpl struct{db NoSQLDatabase})
  - ctx context.Context
  - tripid string
  - coll NoSQLCollection {database = "trainfood", collection = "trainfood"}
  - err .error
.NewTrainFoodServiceImpl(ctx context.Context, db NoSQLDatabase):
  block 0 (Body):
  - ctx context.Context
  - db NoSQLDatabase
