? (*config.ConfigServiceImpl).Create(ctx context.Context, conf config.Config struct{Name string, Value string, Description string}) error:
 block 0 (Body):
  - '[INLINE] db NoSQLDatabase'
  - c (*config.ConfigServiceImpl struct{db NoSQLDatabase})
  - ctx context.Context
  - conf config.Config struct{Name string, Value string, Description string}
  - coll NoSQLCollection {database = "config", collection = "config"}
  - err .error
(*config.ConfigServiceImpl).Delete(ctx context.Context, name string) error:
  block 0 (Body):
  - '[INLINE] db NoSQLDatabase'
  - c (*config.ConfigServiceImpl struct{db NoSQLDatabase})
  - ctx context.Context
  - name string
  - coll NoSQLCollection {database = "config", collection = "config"}
  - err .error
(*config.ConfigServiceImpl).Find(ctx context.Context, name string) (config.Config struct{Name string, Value string, Description string}, error):
 block 0 (Body):
  - '[INLINE] db NoSQLDatabase'
  - c (*config.ConfigServiceImpl struct{db NoSQLDatabase})
  - ctx context.Context
  - name string
  - coll NoSQLCollection {database = "config", collection = "config"}
  - err .error
(*config.ConfigServiceImpl).FindAll(ctx context.Context) ([]config.Config struct{Name string, Value string, Description string}, error):
 block 0 (Body):
  - '[INLINE] db NoSQLDatabase'
  - c (*config.ConfigServiceImpl struct{db NoSQLDatabase})
  - ctx context.Context
  - coll NoSQLCollection {database = "config", collection = "config"}
  - err .error
(*config.ConfigServiceImpl).Update(ctx context.Context, conf config.Config struct{Name string, Value string, Description string}) (bool, error):
 block 0 (Body):
  - '[INLINE] db NoSQLDatabase'
  - c (*config.ConfigServiceImpl struct{db NoSQLDatabase})
  - ctx context.Context
  - conf config.Config struct{Name string, Value string, Description string}
  - coll NoSQLCollection {database = "config", collection = "config"}
  - err .error
config.NewConfigServiceImpl(ctx context.Context, db NoSQLDatabase) ((*config.ConfigServiceImpl struct{db NoSQLDatabase}), error):
  block 0 (Body):
  - ctx context.Context
  - db NoSQLDatabase
