(*trainfood.TrainFoodServiceImpl).Cleanup(ctx context.Context) error:
  block 0 (Body):
  - (-1) [INLINE] db NoSQLDatabase
  - (-1) t (*trainfood.TrainFoodServiceImpl struct{db NoSQLDatabase})
  - (-1) ctx context.Context
  - (-1) coll NoSQLCollection {database = "trainfood", collection = "trainfood"}
  - (-1) err .error
(*trainfood.TrainFoodServiceImpl).CreateTrainFood(ctx context.Context, tf trainfood.TrainFood struct{ID string, TripID string, Foods []food.Food struct{Name string, Price float64}})
  (trainfood.TrainFood struct{ID string, TripID string, Foods []food.Food struct{Name string, Price float64}}, error):
 block 0 (Body):
  - (-1) [INLINE] db NoSQLDatabase
  - (-1) t (*trainfood.TrainFoodServiceImpl struct{db NoSQLDatabase})
  - (-1) ctx context.Context
  - (-1) tf trainfood.TrainFood struct{ID string, TripID string, Foods []food.Food struct{Name string, Price float64}}
  - (-1) coll NoSQLCollection {database = "trainfood", collection = "trainfood"}
  - (-1) err .error
(*trainfood.TrainFoodServiceImpl).ListTrainFood(ctx context.Context) ([]trainfood.TrainFood struct{ID string, TripID string, Foods []food.Food struct{Name string, Price float64}}, error):
 block 0 (Body):
  - (-1) [INLINE] db NoSQLDatabase
  - (-1) t (*trainfood.TrainFoodServiceImpl struct{db NoSQLDatabase})
  - (-1) ctx context.Context
  - (-1) coll NoSQLCollection {database = "trainfood", collection = "trainfood"}
  - (-1) err .error
(*trainfood.TrainFoodServiceImpl).ListTrainFoodByTripID(ctx context.Context, tripid string) ([]food.Food struct{Name string, Price float64}, error):
 block 0 (Body):
  - (-1) [INLINE] db NoSQLDatabase
  - (-1) t (*trainfood.TrainFoodServiceImpl struct{db NoSQLDatabase})
  - (-1) ctx context.Context
  - (-1) tripid string
  - (-1) coll NoSQLCollection {database = "trainfood", collection = "trainfood"}
  - (-1) err .error
trainfood.NewTrainFoodServiceImpl(ctx context.Context, db NoSQLDatabase) ((*trainfood.TrainFoodServiceImpl struct{db NoSQLDatabase}), error):
 block 0 (Body):
  - (-1) ctx context.Context
  - (-1) db NoSQLDatabase
