(*trainfood.TrainFoodServiceImpl).Cleanup(ctx context.Context) error:
  block 0 (Body):
  - '[INLINE] db NoSQLDatabase'
  - t (*trainfood.TrainFoodServiceImpl struct{db NoSQLDatabase})
  - ctx context.Context
  - coll NoSQLCollection {database = "trainfood", collection = "trainfood"}
  - err .error
(*trainfood.TrainFoodServiceImpl).CreateTrainFood(ctx context.Context, tf trainfood.TrainFood struct{ID string, TripID string, Foods []food.Food struct{Name string, Price float64}})
  (trainfood.TrainFood struct{ID string, TripID string, Foods []food.Food struct{Name string, Price float64}}, error):
 block 0 (Body):
  - '[INLINE] db NoSQLDatabase'
  - t (*trainfood.TrainFoodServiceImpl struct{db NoSQLDatabase})
  - ctx context.Context
  - tf trainfood.TrainFood struct{ID string, TripID string, Foods []food.Food struct{Name string, Price float64}} --> (TAINTED 1x) --> [TRAINFOOD_DB.TrainFood]
  - coll NoSQLCollection {database = "trainfood", collection = "trainfood"}
  - err .error
(*trainfood.TrainFoodServiceImpl).ListTrainFood(ctx context.Context) ([]trainfood.TrainFood struct{ID string, TripID string, Foods []food.Food struct{Name string, Price float64}}, error):
 block 0 (Body):
  - '[INLINE] db NoSQLDatabase'
  - t (*trainfood.TrainFoodServiceImpl struct{db NoSQLDatabase})
  - ctx context.Context
  - coll NoSQLCollection {database = "trainfood", collection = "trainfood"}
  - err .error
(*trainfood.TrainFoodServiceImpl).ListTrainFoodByTripID(ctx context.Context, tripid string) ([]food.Food struct{Name string, Price float64}, error):
 block 0 (Body):
  - '[INLINE] db NoSQLDatabase'
  - t (*trainfood.TrainFoodServiceImpl struct{db NoSQLDatabase})
  - ctx context.Context
  - tripid string
  - coll NoSQLCollection {database = "trainfood", collection = "trainfood"}
  - err .error
trainfood.NewTrainFoodServiceImpl(ctx context.Context, db NoSQLDatabase) ((*trainfood.TrainFoodServiceImpl struct{db NoSQLDatabase}), error):
 block 0 (Body):
  - ctx context.Context
  - db NoSQLDatabase
